import type { Metadata } from "next";
import { Jost, Merriweather } from "next/font/google";
import "./globals.css";
import "./style.css";
import Navbar from "./components/Navbar";

const jost = Jost({ subsets: ["latin"] });
const merriweather = Merriweather({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} ${merriweather.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
